spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy_tra?serverTimezone=UTC
    username: root
    password: 1234


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

  sql:
    init:
      mode: always

file:
  path:
    /Users/joonhyoungjeon/Documents/GitHub/Toy_Finder/Toy_Finder